version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
      - 8888:8888
    networks:
      - shared
    depends_on:
      - influx
      - mysql
    environment:
      WAIT_HOSTS: influx:8086, mysql:3306
  influx:
    image: influxdb:alpine
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    networks:
      - shared
  mysql:
    image: mariadb:10.1.38
#    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hose
    networks:
      - shared
networks:
  shared:
    driver: bridge
