---

- name: Install MySQL
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  vars:
    item:
      - python-mysqldb
      - default-mysql-server
#  notify:
#    - start mysql

- name: Start MySQL
  service:
    name: mysql
    state: started

- name: Set MySQL root password
  mysql_user:
    check_implicit_admin: yes
    user: root
    password: "{{ mysql_root_password }}"
    host: "{{ item }}"
    priv: '*.*:ALL,GRANT'
    state: present
  with_items:
    - localhost
    - 127.0.0.1
    - "{{ ansible_hostname }}"
  notify:
    - restart mysql

- name: Create default Database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_hose_database }}"
    state: present

- name: Create default user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_hose_user }}"
    password: "{{ mysql_hose_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
  notify:
    - restart mysql

- name: Ensure Anonymous MySQL user(s) are not in the database
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
  notify:
    - restart mysql
