---

- name: Add NodeJs LTS gpg key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeJs repo
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_major_version }}.x xenial main"
    state: present
    update_cache: yes

- name: Install NodeJs
  apt:
    name: nodejs
    state: present
