---

- name: Clone repository
  git:
    repo: "{{ app_git_repo }}"
    dest: "{{ app_git_dest }}"
    version: "{{ app_git_version }}"

- name: Install backend dependencies
  yarn:
    path: "{{ app_git_dest }}/backend"
    production: yes
    state: present
