---

- name: Add InfluxDB gpg key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Add InfluxDB repo
  apt_repository:
    repo: "deb https://repos.influxdata.com/ubuntu trusty stable"
    state: present
    update_cache: yes

- name: Install InfluxDB
  apt:
    name: influxdb
    state: present


- name: Update InfluxDB hostname
  replace:
    dest=/etc/influxdb/influxdb.conf
    regexp='hostname = "localhost"'
    replace='hostname = "{{ ansible_hostname }}"'
    backup=yes
  notify:
    - restart influxdb


