version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/opt/app
      - /opt/app/node_modules
    ports:
      - 5000:5000
      - 8888:8888
    networks:
      - shared
  influx:
    image: influxdb:alpine
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    networks:
      - shared
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hose
      MYSQL_USER: hose
      MYSQL_PASSWORD: secret
    networks:
      - shared
networks:
  shared:
    driver: bridge


